spirit_dev_ci_hub_post:
    resource: "@SpiritDevCIHubPostBundle/Controller/PostController.php"
    type:     annotation

spirit_dev_ci_hub_post_difflist:
    resource: "@SpiritDevCIHubPostBundle/Controller/DiffListController.php"
    prefix:   /difflist
    type:     annotation